### ISSUE TITLE
Production Build environment variables

### ISSUE THREAD

**Issue by baj84** [jaredpalmer/razzle#1225] opened 2020-04-02 05:09 UTC
Hey,

When I do a production build the environment variables in my .env are not available.

My .env contains:
`API_URL=http://localhost:9999/api`

Then in my server.js I'm trying to access via:
`process.env.API_URL`

This works when I do a development build: `npm run start`

What am i missing?
Cheers

**Comment by nimaa77** [comment] 2020-04-07 21:49
hello, you have to prefix env variables with `RAZZLE_`

```
// .env
// you can access this value using process.env.RAZZLE_API_URL
RAZZLE_API_URL=http://localhost:9999/api
```

**Comment by fivethreeo** [comment] 2020-04-09 00:04
I think the confusion here is about build time and runtime variables.

https://gist.github.com/fivethreeo/a1717cef2363783d73b6dd018b621a11

**Comment by baj84** [comment] 2020-04-09 00:13
Thanks guys. My issue was that I am unable to access process.env variables programmatically, .e.g. this doesn't work:

const key = 'RAZZLE_API_URL' ;
const val = process.env[key];

**Comment by fivethreeo** [comment] 2020-04-13 03:50
The dotenv files are only loaded at build time so they do not exist as env vars in production if you define them in dotenv. They have to be set in the environment. So you cannot access those programmatically.  Also that code cannot work in the browser if you need the api url there. This is not a bug. You need to add runtime config to your app.

**Comment by fivethreeo** [comment] 2020-05-09 14:33
Resolved, closing

**Closed as completed by fivethreeo** 2020-05-09 14:33 UTC
