### ISSUE TITLE
Browser reloads after Server recompiles but before Client recompiles, shows old content

### ISSUE THREAD

**Issue by speedy250** [jaredpalmer/razzle#925] opened 2019-02-13 21:53 UTC
**Issue:**
During development, old content is (occasionally) shown after saving, forcing dev to manually refresh the page to view latest app version.

**Theory**
I think this issue has been reported as a local cache issue previously, but I don't think that is the issue. In development mode after modification, the site reloads its modules and refreshes any connected browser. Occasionally, the "new" content shown is one build behind. My theory is that the site reload triggers before the client app is finished compiling, resulting in old content being shown to the developer.

I've uploaded a screen cap to Vimeo here: https://vimeo.com/user95078979/review/317133063/de27f344eb

The screen cap shows two changes are made: Darken the Title and modify the text to say "HI". After saving, I click to the razzle cmd window, which shows that the server compiles, the page reloads, then the client finishes compiling about 6 seconds after! Then I try to highlight that the text style is darker, but the text remains unchanged. Finally, I manually refresh the page to show that "HI" is now present.

I haven't had the chance to create a test repo, and it may be compile-time-length related, so I'm afraid I don't have anything for you in that way.

**Comment by krvajal** [comment] 2019-04-22 20:55
I can confirm this as well.

**Comment by krvajal** [comment] 2019-08-10 20:47
Any pointer on how to solve this @jaredpalmer? I can work on a fix but need some guidance.

**Comment by aswin-s** [comment] 2019-11-12 04:54
I'm still facing this issue. Happy to help if someone can point me in the right direction

**Comment by nimaa77** [comment] 2020-03-17 21:40
duplicate of #1069, let's move all conversations in that issue so we have everything in one place

**Closed as completed by nimaa77** 2020-03-17 21:40 UTC
Labels: bug, duplicate

**Comment by krvajal** [comment] 2020-03-17 21:50
Chronologically speaking the issue you are mentioning is the duplicated one.

**Comment by nimaa77** [comment] 2020-03-17 21:53
@krvajal yeah, you are right, but there is no difference :)

let's focus and fix this bug

**Comment by krvajal** [comment] 2020-03-17 21:54
Let me know if I can help somehow

**Comment by nimaa77** [comment] 2020-04-08 00:31
@krvajal https://github.com/jaredpalmer/razzle/issues/992#issuecomment-501119226

**Comment by zpetukhov** [comment] 2020-06-10 23:10
I was developing an app with razzle and hapi instead of express.
And faced with the described issue.
(BTW #1069 does not look as duplicate from the first sight)
I have tried all the options I could find... no luck.
As a temporary dirty hack I did the following:
file: node_modules/webpack/hot/dev-server.js
replace this:
window.location.reload();
to:
setTimeout('window.location.reload()',1100);

There's two occurences...
In my case the second one is the needed one (in 'catch' section).

If someone will find a better solution - let me know please!
